from misc import *
import os.path, shutil

def output_thes(filename, filename_output, output_all=False):
  with open(filename_output, 'w') as f2:
    with open(filename, 'r') as f:
      for l in f:
        fn, om = l.replace('\n', '').split('\t\t')
        if ', the' in om or ', a' in om:
          f2.write("%s\t\t%s\n" % (fn, MQuote.clean_movie_title(om)))
        elif output_all:
          f2.write("%s\t\t%s\n" % (fn, om))

# Copy Thes Into Another Directory
def copy_into_new_directory(directory, names_file):
  dir = directory+'/thes'
  if not os.path.exists(dir):
    os.makedirs(dir)
  with open(names_file, 'r') as f:
    for l in f:
      fn, om = l.replace('\n', '').split('\t\t')
      try:
        shutil.move(directory+'/'+fn+'.bing.sqlite', directory+'/thes/'+fn+'.bing.sqlite')
      except Exception as detail:
        print "Exception: ", detail

# Merge Bing Random Quote DBs generated by names.txt and names_thes.txt 
def merge_names_db_thes(names_db_filename, thes_db_filename):
  shutil.copyfile(names_db_filename, names_db_filename+'.merged')
  ndb = MDb.MDb(names_db_filename+'.merged')
  tdb = MDb.MDb(thes_db_filename)
  thes_results = tdb.q('SELECT movie, actor, quote, source, quote_type, query_type, result, urls FROM quotes')
  for movie_name, movie_filename, quote, source, quote_type, query_type, result, urls in thes_results:
    ndb.qt('UPDATE quotes SET result=?, urls=?, movie=? WHERE actor=? AND quote=? AND source=? AND quote_type=? AND query_type=?', (result, urls, movie_name, movie_filename, quote, source, quote_type, query_type))
  ndb.commit()
  ndb.close()
  tdb.close()

# output_thes('../data/scripts/names.txt', '../data/scripts/names_thes.txt')
# output_thes('../data/scripts/names.txt', '../data/scripts/names_merged.txt', output_all=True)
# output_thes('../data/scripts/names_cham_unique_dedup.txt', '../data/scripts/names_cham_unique_dedup_thes.txt')
# copy_into_new_directory('../data/scripts/db', '../data/scripts/names_thes.txt')
# copy_into_new_directory('../data/scripts/db', '../data/scripts/names_cham_unique_dedup_thes.txt')
  
# merge_names_db_thes('../data/scripts/db/names.bing.sqlite', '../data/scripts/db/names_thes.bing.sqlite')